/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fecs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author nandana and yashraj
 */
public class footprintCalculator extends javax.swing.JFrame {
    
    public static String currentUser;
    public static String nameUser;
    public static float[] curUserData = new float[6];

    /**
     * Creates new form footprintCalculator
     */
    public footprintCalculator(String user, String name) {
        
        initComponents();
        currentUser=user;
        nameUser=name;
        loginStatus.setText("Logged in as, "+nameUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petrol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        electricity = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        diesel = new javax.swing.JTextField();
        lpg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cng = new javax.swing.JTextField();
        loginStatus = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        petrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petrolActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter your monthly eletricity consumption ( In KWHr or Units per month) ");

        jLabel2.setText("Enter your weekly deisel consumption ( In litres per week)");

        jLabel3.setText("Enter your monthly LPG Consumption (In litres per month ) (One cylinder=14L)");

        jLabel4.setText("Enter your weekly petrol consumption ( In litres per week)");

        electricity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricityActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        diesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieselActionPerformed(evt);
            }
        });

        lpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpgActionPerformed(evt);
            }
        });

        jLabel5.setText("In case you do not consume any of the above, please fill a zero in the text field.");

        resetButton.setText("Reset");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter your monthly CNG Consumption (in Kgs per week)");

        cng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cngActionPerformed(evt);
            }
        });

        loginStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setText("Detailed Analysis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(diesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(petrol, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(electricity, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lpg)
                                            .addComponent(cng))))))
                        .addGap(11, 11, 11)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(616, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(133, 133, 133)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton7))
                    .addComponent(loginStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petrolActionPerformed

    private void electricityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricityActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void dieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dieselActionPerformed

    private void lpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpgActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed

        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/FECS", "root", "root");
            Statement s = c.createStatement();
            
            String electricity_value=electricity.getText();
            String petrol_value=petrol.getText();
            String diesel_value=diesel.getText();
            String lpg_value=lpg.getText();
            String cng_value=cng.getText();
            try
            { int electricity_value_int=Integer.parseInt(electricity_value);
            int petrol_value_int=Integer.parseInt(petrol_value);
            int diesel_value_int=Integer.parseInt(diesel_value);
            int lpg_value_int=Integer.parseInt(lpg_value);
            int cng_value_int=Integer.parseInt(cng_value);}
            catch (NumberFormatException e)
            {warningLabel.setText("Kindly fill all numbers");} 
        
            float electricity_emission=(float)(Integer.parseInt(electricity_value)*12*0.85);
            float petrol_emission=(float)(Integer.parseInt(petrol_value)*52*2.296);
            float diesel_emission=(float)(Integer.parseInt(diesel_value)*52*2.653);
            float lpg_emission=(float)(Integer.parseInt(lpg_value)*12*2.983);
            float cng_emission=(float)(Integer.parseInt(cng_value)*12*2.983);
            float footprint= (electricity_emission+petrol_emission+diesel_emission+lpg_emission+cng_emission)/1000;
            s.executeUpdate("insert into footprintDetails values('" + currentUser + "','" + electricity_emission + "','"+ petrol_emission + "','" + diesel_emission + "','" + lpg_emission + "','" + cng_emission + "','" + footprint+ "')");
            
            curUserData[0]=electricity_emission;
            curUserData[1]=petrol_emission;
            curUserData[2]=diesel_emission;
            curUserData[3]=lpg_emission;
            curUserData[4]=cng_emission;
            curUserData[5]=footprint;
            
            if ((footprint>=1.5)&&(electricity_emission>petrol_emission)&&(electricity_emission>diesel_emission)&&(electricity_emission>lpg_emission)&&(electricity_emission>cng_emission)){
            warningLabel.setText("Your carbon footprint is above India's average. It is recommended you cut down on your electricity consumption.");}
            
            if ((footprint>=1.5)&&(lpg_emission>electricity_emission)&&(lpg_emission>diesel_emission)&&(lpg_emission>cng_emission)&&(lpg_emission>petrol_emission)){
            warningLabel.setText("Your carbon footprint is above India's average. It is recommended you cut down on your LPG consumption.");}
            
            if ((footprint>=1.5)&&(cng_emission>petrol_emission)&&(cng_emission>diesel_emission)&&(cng_emission>lpg_emission)&&(cng_emission>electricity_emission)){
            warningLabel.setText("Your carbon footprint is above India's average. It is recommended you cut down on your CNG consumption.");}
            
            if ((footprint>=1.5)&&(petrol_emission>electricity_emission)&&(petrol_emission>diesel_emission)&&(petrol_emission>lpg_emission)&&(petrol_emission>cng_emission)){
            warningLabel.setText("Your carbon footprint is above India's average. It is recommended you cut down on your Petrol consumption.");}
            
            if ((footprint>=1.5)&&(diesel_emission>petrol_emission)&&(diesel_emission>electricity_emission)&&(diesel_emission>lpg_emission)&&(diesel_emission>cng_emission)){
            warningLabel.setText("Your carbon footprint is above India's average. It is recommended you cut down on your Diesel consumption.");}
            
            if (footprint<1.5){
            warningLabel.setText("Congratulations !! Your carbon footprint is less than India's average.");}
            
            
            if (footprint==1.5){
            warningLabel.setText("Your carbon footprint is equivalent to India's average.");}
            
            c.close();
        }
        
        
        catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_calculateButtonActionPerformed
    
    private void cngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cngActionPerformed

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
    diesel.setText("");
    petrol.setText("");
    lpg.setText("");
    cng.setText("");
    electricity.setText("");
    }//GEN-LAST:event_resetButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        postLogin p = new postLogin(currentUser, nameUser);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        currentUser = null;
        loginPage l = new loginPage();
        this.setVisible(false);
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showFootprint sf = new showFootprint(curUserData);
        sf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(footprintCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(footprintCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(footprintCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(footprintCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new footprintCalculator(currentUser, nameUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField cng;
    private javax.swing.JTextField diesel;
    private javax.swing.JTextField electricity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel loginStatus;
    private javax.swing.JTextField lpg;
    private javax.swing.JTextField petrol;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
