/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fecs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Nandana and Yash Raj
 */
public class showFootprint extends javax.swing.JFrame {

    public static float[] curUserData = new float[6];
    /**
     * Creates new form showFootprint
     */
    public showFootprint(float[] data) {
        initComponents();
        curUserData = data;
        String avgElectricity = null, avgPetrol = null, avgDiesel = null, avgLPG = null, avgCNG = null, avgFootprint = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/FECS","root","root");
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("select avg(electricity), avg(petrol), avg(diesel), avg(lpg), avg(cng), avg(footprint) from footprintDetails");
            while(rs.next()){
                avgElectricity = Double.toString(rs.getDouble("avg(Electricity)"));
                avgPetrol = Double.toString(rs.getDouble("avg(Petrol)"));
                avgDiesel = Double.toString(rs.getDouble("avg(Diesel)"));
                avgLPG = Double.toString(rs.getDouble("avg(LPG)"));
                avgCNG = Double.toString(rs.getDouble("avg(CNG)"));
                avgFootprint = Double.toString(rs.getDouble("avg(footprint)"));
            }
            resultArea.setText("The results are as below: \n"
                              +"Fields\t\t"+"Average for all users\t"+"Your consumption\n"
                              +"Electricity\t\t"+avgElectricity+"\t\t"+curUserData[0]+"\n"
                              +"Petrol\t\t"+avgPetrol+"\t\t"+curUserData[1]+"\n"
                              +"Diesel\t\t"+avgDiesel+"\t\t"+curUserData[2]+"\n"
                              +"LPG\t\t"+avgLPG+"\t\t"+curUserData[3]+"\n"
                              +"CNG\t\t"+avgCNG+"\t\t"+curUserData[4]+"\n"
                              +"Footprint\t\t"+avgFootprint+"\t\t"+curUserData[5]+"\n"
                              +"And the National Average Footprint is 1.5 tonnes/per capita/per annum.\n"
                              +"Now look at your data and please help reduce the overall Carbon Dioxide Generated."
            );
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showFootprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showFootprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showFootprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showFootprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showFootprint(curUserData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultArea;
    // End of variables declaration//GEN-END:variables
}
